// Auto-generated by Supabase CLI — this is a placeholder until we run gen types
// Replace this file after running: npx supabase gen types typescript --linked
export type Database = Record<string, any>
